### ISSUE TITLE
readme 乱码

### ISSUE THREAD

**Issue by sunslj** [daili0015/Download_1024#2]
readme 乱码，想问下直接用官网地址行不行，为什么的运行后提示有语法错误。

Traceback (most recent call last):
  File "D:\软件\Download_1024-master\test1.py", line 8, in <module>
    from zcy_fun import get_format_filename
  File "D:\软件\Download_1024-master\zcy_fun.py", line 4, in <module>
    from proxytest import download_single_image
  File "D:\软件\Download_1024-master\proxytest.py", line 95
    return = download_single_image(image_url, proxy_flag=True, try_time=(try_time + 1))
           ^
SyntaxError: invalid syntax

**Comment by daili0015** [comment]
readme里的内容复制进来，readme.decode('utf-8')就是字符串了，原本是utf-8编码的字节。里面有写地址，或者在网页主界面点“日本骑兵”，或“亚洲无码”进去复制网址，粘贴进去。另外存储位置也要改下

**Comment by Orangels** [comment]
请问 这个引用方法报错这个 什么原因?  报错和上面的一样

**Comment by Orangels** [comment]
谢谢楼主的分享,已经解决了, renturn 那里语法错误,去掉 = 就可以运行了

**Comment by pokerstarxy** [comment]
有个问题，如果单使用复制readme内容，并通过decode解码可以输出中文，但是如果强迫症犯了， 非要使用 文本读取，并输出，该怎么办，网上找不到处理的办法。。请老司机带带我
![default](https://cloud.githubusercontent.com/assets/16798673/21356798/da258a22-c70d-11e6-9482-de8a8bec5aea.png)
